org.gradle.jvmargs = -Xmx2G
org.gradle.configureondemand=true
targetJavaVersion = 21

# mod base properties
modName = Damage Number Particles
modDescription = Displays floating number particles whenever an entity takes damage or receives healing
modid = dnp
modLicense = GNU General Public License v3.0
mavenGroup = io.github.smootheez

# fabric default dependencies property
loaderVersion = 0.18.4
loomVersion = 1.14-SNAPSHOT

# modrinth
modrinthId = suhHDmmN

# curseforge
curseforgeId = 1317676